# Generated by RationaleVault 2.0
# Projection template version 1

"""Example Projection implementation."""
from __future__ import annotations

from typing import Any, Optional

from rationalevault.projection_platform import (
    Projection,
    ProjectionCapabilities,
    ProjectionHealth,
    ProjectionMetadata,
    EventSelector
)
from rationalevault.schema import EventRecord

from .events import TaskCreatedPayload, TaskCompletedPayload
from .state import GoldenProjState, TaskItem


# Decision:
# Projections are objects that implement the Projection protocol.
# They are not registered magically via decorators. 
#
# Why:
# Explicit dependency wiring is required by ADR-027. We must be able to 
# reason about dependencies and build order purely statically.

class GoldenProjProjection(Projection):
    """Materializes a state of all tasks from the event stream."""
    
    def __init__(self) -> None:
        self._health = ProjectionHealth.UNKNOWN

    @property
    def metadata(self) -> ProjectionMetadata:
        return ProjectionMetadata(
            id="golden_proj",
            version=1,
            schema_version=1,
            consumed_events=EventSelector(),
            capabilities=ProjectionCapabilities(),
            description="Tracks open and completed tasks.",
        )

    def initialize(self, ctx: Any) -> None:
        self._health = ProjectionHealth.READY

    # Decision:
    # Reducers are purely functional and accept the state and a batch of events.
    # They return the mutated state. They NEVER perform I/O.
    #
    # Why:
    # If a reducer performed an HTTP request, replaying 100,000 events would
    # DDOS the external API and the resulting state would depend on the network,
    # destroying the determinism guarantee.
    def reduce(self, events: list[EventRecord], initial_state: Optional[Any] = None) -> GoldenProjState:
        state = initial_state if initial_state is not None else GoldenProjState()
        
        for event in events:
            if event.event_type == "TaskCreated":
                payload = TaskCreatedPayload.from_dict(event.payload)
                state.tasks[payload.task_id] = TaskItem(
                    id=payload.task_id,
                    description=payload.description,
                    owner=payload.owner,
                    completed=False,
                )
            elif event.event_type == "TaskCompleted":
                payload = TaskCompletedPayload.from_dict(event.payload)
                if payload.task_id in state.tasks:
                    state.tasks[payload.task_id].completed = True
        return state

    def serialize(self, state: Any) -> dict:
        if not isinstance(state, GoldenProjState):
            return {}
        return {
            "tasks": {
                k: {"id": v.id, "description": v.description, "owner": v.owner, "completed": v.completed}
                for k, v in state.tasks.items()
            }
        }

    def deserialize(self, payload: dict) -> Any:
        state = GoldenProjState()
        if "tasks" in payload:
            for k, v in payload["tasks"].items():
                state.tasks[k] = TaskItem(
                    id=v["id"],
                    description=v["description"],
                    owner=v["owner"],
                    completed=v.get("completed", False)
                )
        return state

    def health(self) -> ProjectionHealth:
        return self._health

    def shutdown(self) -> None:
        self._health = ProjectionHealth.SHUTDOWN
