"""
Unit tests for OrganizationGraphState serialization and backward compatibility.
"""
from __future__ import annotations

import json
from pathlib import Path
from rationalevault.organization.graph import OrganizationGraphState, OrganizationNode, OrganizationEdge, OrganizationGraphHealth
from rationalevault.organization.relation_types import OrganizationRelationType


def test_graph_state_serialization_invariants():
    nodes = {
        "proj-a": OrganizationNode("proj-a", "Project A", 3, 1, 1, 0, True, 1.0)
    }
    edges = [
        OrganizationEdge("proj-a", "proj-b", OrganizationRelationType.IN_CLUSTER, 1.0, 0.8)
    ]
    health = OrganizationGraphHealth(1.0, 0.5, 0.0, 1.0, 1.0, 0.9)

    state = OrganizationGraphState(
        compiled_at="2026-06-24T12:00:00Z",
        projection_version="1.0",
        nodes=nodes,
        edges=edges,
        adjacency={},  # Recomputed dynamically in from_dict
        reverse_adjacency={},
        clusters=[["proj-a", "proj-b"]],
        density=0.5,
        conflicted_nodes=set(),
        edges_by_relation={OrganizationRelationType.IN_CLUSTER: (edges[0],)},
        knowledge_flow_balance={"proj-a": 1},
        knowledge_producers=[("proj-a", 1.0)],
        knowledge_consumers=[],
        contradiction_hotspots=[],
        health=health,
    )

    # 1. Roundtrip invariant
    serialized = state.to_dict()
    deserialized = OrganizationGraphState.from_dict(serialized)

    assert deserialized.compiled_at == state.compiled_at
    assert deserialized.projection_version == state.projection_version
    assert "proj-a" in deserialized.nodes
    assert len(deserialized.edges) == 1
    assert deserialized.edges[0].relation_type == OrganizationRelationType.IN_CLUSTER

    # 2. JSON compatibility
    json_str = json.dumps(serialized)
    json_dict = json.loads(json_str)
    assert json_dict == serialized

    # 3. Normalization Invariant
    # Clear out empty dictionary differences generated by mapping rebuilds if any
    assert deserialized.to_dict() == serialized


def test_graph_state_v1_backward_compatibility():
    fixture_path = Path(__file__).parents[2] / "fixtures" / "schema_v1" / "graph_state_v1.json"
    assert fixture_path.exists(), "Graph state fixture v1 should exist"

    with open(fixture_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    assert data.get("schema_version") == 1

    # Load from legacy dict
    state = OrganizationGraphState.from_dict(data)
    assert state.compiled_at == "2026-06-24T12:00:00Z"
    assert "proj-a" in state.nodes
    assert state.nodes["proj-a"].name == "Project A"
    assert len(state.edges) == 1
    assert state.edges[0].relation_type == OrganizationRelationType.IN_CLUSTER

    # Verify serialization equivalence
    serialized_again = state.to_dict()
    loaded_again = OrganizationGraphState.from_dict(serialized_again)
    assert loaded_again.to_dict() == serialized_again
