"""
Claude Agent Compiler.

Produces a RationaleVault Context Block optimized for Claude's narrative reasoning style.

Section order (per design freeze, Change 6):
  1. Header (project, ledger version, timestamp)
  2. ⚠️  Open Questions  ← HIGHEST PRIORITY — resolve before starting new tasks
  3. 🚫  Blocked Tasks   (tasks with unresolved open question blockers)
  4. 📋  Active Tasks    (unblocked tasks, priority sorted)
  5. ✅  Accepted Decisions  (architectural guardrails — do not reverse)
  6. 📌  Project Context (goal + current focus)
  7. 🚀  Resumption Prompt  (actionable handoff instruction)

Design principles:
  - Output-only. No Anthropic API calls. RationaleVault is model-agnostic.
  - Paste the output at the top of a Claude conversation.
  - Resumption prompt targets the highest-priority open question first,
    then the highest-priority task if no questions remain.
  - Accepted decisions are labeled with explicit non-reversal warnings —
    a common failure mode in multi-agent handoffs.
"""
from __future__ import annotations

from rationalevault.cognitive_head.compiler import CognitiveHead
from rationalevault.cognitive_head.reducers import DecisionState, QuestionState, TaskState
from rationalevault.compilers.base import AgentCompiler

_PRIORITY_ICONS = {
    "critical": "🔴",
    "high": "🟡",
    "normal": "🔵",
    "low": "⚪",
}

_STATUS_ICONS = {
    "open": "○",
    "in_progress": "◑",
    "blocked": "⊗",
    "completed": "✓",
}


class ClaudeCompiler(AgentCompiler):
    """
    Compiles RationaleVault state into a markdown context block for Claude.

    Optimized for:
      - Narrative reasoning
      - Architecture analysis
      - Research and synthesis
      - Multi-agent handoff continuity
    """

    @property
    def agent_name(self) -> str:
        return "Claude"

    def compile(self, head: CognitiveHead) -> str:
        sections = [
            self._header(head),
            self._open_questions(head),
            self._blocked_tasks(head),
            self._active_tasks(head),
            self._decisions(head),
            self._project_context(head),
            self._resumption_prompt(head),
        ]
        return "\n\n".join(s for s in sections if s.strip())

    # ── Section builders ───────────────────────────────────────────────────

    def _header(self, head: CognitiveHead) -> str:
        return (
            f"# 🔁 RationaleVault Context — {head.project_name}\n"
            f"> **Ledger v{head.ledger_version}** · compiled {head.compiled_at}\n"
            f">\n"
            f"> ⚡ This context was generated by RationaleVault from the immutable event ledger.\n"
            f"> It is authoritative. Do **not** re-derive information already present here."
        )

    def _open_questions(self, head: CognitiveHead) -> str:
        if not head.open_questions:
            return (
                "## ⚠️ Open Questions\n"
                "_None. All questions resolved. Proceed to active tasks._"
            )

        lines = [
            "## ⚠️ Open Questions  ← RESOLVE THESE BEFORE STARTING NEW TASKS",
            "",
            "> Unresolved questions are the primary cause of wasted agent context.",
            "> Address the highest-priority question first.",
        ]
        for q in head.open_questions:
            icon = _PRIORITY_ICONS.get(q.priority, "🔵")
            lines.append(f"\n### {icon} [{q.priority.upper()}] {q.title}")
            lines.append(f"**ID:** `{q.question_id}`  |  **Raised by:** {q.raised_by or 'unknown'}")
            if q.description:
                lines.append(f"\n{q.description}")
            if q.blocks_task_ids:
                task_refs = ", ".join(f"`{t}`" for t in q.blocks_task_ids)
                lines.append(f"\n**⛔ Blocks tasks:** {task_refs}")

        return "\n".join(lines)

    def _blocked_tasks(self, head: CognitiveHead) -> str:
        if not head.blockers:
            return ""

        lines = ["## 🚫 Blocked Tasks"]
        for b in head.blockers:
            q_refs = ", ".join(f"`{q}`" for q in b["blocked_by_questions"])
            lines.append(f"- **{b['task_title']}** (`{b['task_id']}`)")
            lines.append(f"  ↳ Blocked by: {q_refs}")
        return "\n".join(lines)

    def _active_tasks(self, head: CognitiveHead) -> str:
        blocked_ids = {b["task_id"] for b in head.blockers}
        unblocked = [t for t in head.active_tasks if t.task_id not in blocked_ids]

        if not unblocked:
            return (
                "## 📋 Active Tasks\n"
                "_No unblocked tasks. Resolve open questions first._"
            )

        lines = ["## 📋 Active Tasks"]
        for t in unblocked:
            status_icon = _STATUS_ICONS.get(t.status, "○")
            priority_badge = (
                f" **[{t.priority.upper()}]**" if t.priority != "normal" else ""
            )
            lines.append(f"\n### {status_icon}{priority_badge} {t.title}")
            lines.append(f"**ID:** `{t.task_id}`  |  **Status:** {t.status}")
            if t.description:
                lines.append(f"\n{t.description}")
            if t.assignee:
                lines.append(f"\n**Assignee:** {t.assignee}")
            if t.tags:
                lines.append(f"**Tags:** {', '.join(t.tags)}")

        return "\n".join(lines)

    def _decisions(self, head: CognitiveHead) -> str:
        if not head.active_decisions:
            return (
                "## ✅ Accepted Decisions\n"
                "_No accepted decisions yet._"
            )

        lines = [
            "## ✅ Accepted Decisions  ← DO NOT REVERSE WITHOUT STRONG REASON",
            "",
            "> These decisions represent architectural guardrails.",
            "> Reversing them requires explicit justification and a new DECISION_SUPERSEDED event.",
        ]
        for d in head.active_decisions:
            lines.append(f"\n### {d.title}")
            lines.append(f"**ID:** `{d.decision_id}`  |  **Decided by:** {d.created_by or 'unknown'}")
            if d.description:
                lines.append(f"\n{d.description}")
            if d.rationale:
                lines.append(f"\n**Rationale:** {d.rationale}")

        return "\n".join(lines)

    def _project_context(self, head: CognitiveHead) -> str:
        return "\n".join([
            "## 📌 Project Context",
            f"**Goal:** {head.project_goal}",
            "",
            f"**Current Focus:** {head.current_focus}",
        ])

    def _resumption_prompt(self, head: CognitiveHead) -> str:
        # Determine what to do next
        if head.open_questions:
            first_q = head.open_questions[0]
            next_action = f'Resolve the open question: **"{first_q.title}"**'
            next_detail = (
                f"This is a {first_q.priority}-priority question. "
                f"It was raised by {first_q.raised_by or 'a previous agent'}. "
                + (f"It blocks tasks: {', '.join(first_q.blocks_task_ids)}."
                   if first_q.blocks_task_ids else "")
            )
        elif head.active_tasks:
            first_task = next(
                (t for t in head.active_tasks
                 if not any(b["task_id"] == t.task_id for b in head.blockers)),
                head.active_tasks[0]
            )
            next_action = f'Continue work on task: **"{first_task.title}"**'
            next_detail = (
                f"Priority: {first_task.priority}. Status: {first_task.status}."
            )
        else:
            next_action = "Review project state and propose the next sprint."
            next_detail = "All current tasks are complete. Propose what to build next."

        return "\n".join([
            "---",
            "## 🚀 Resumption Prompt",
            "",
            f"You are resuming work on **{head.project_name}**.",
            f"Ledger version: **{head.ledger_version}**",
            "",
            f"**Your immediate next action:** {next_action}",
            f"{next_detail}",
            "",
            "**Instructions:**",
            "1. Do not re-derive information already present in this context.",
            "2. Resolve open questions **before** creating new tasks.",
            "3. Respect all accepted decisions — they are architectural guardrails.",
            "4. When you complete work, record new events back to RationaleVault.",
            "5. If you identify new open questions, raise them explicitly.",
        ])
