"""
Scaffolding Engine.

Reads canonical examples and renders them to the destination directory,
substituting names and injecting metadata.
"""
import os
import shutil
from pathlib import Path
from typing import Dict

def render_scaffold(
    template_dir: Path,
    dest_dir: Path,
    substitutions: Dict[str, str],
    is_projection: bool = True
) -> None:
    """
    Renders a scaffold from a template directory to a destination.
    """
    if not template_dir.exists():
        raise FileNotFoundError(f"Template directory not found: {template_dir}")

    dest_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate metadata header
    if is_projection:
        header = "# Generated by RationaleVault 2.0\n# Projection template version 1\n"
    else:
        header = "# Generated by RationaleVault 2.0\n# Skill template version 1\n"
        
    for root, dirs, files in os.walk(template_dir):
        # Exclude pycache
        if "__pycache__" in dirs:
            dirs.remove("__pycache__")
            
        rel_dir = Path(root).relative_to(template_dir)
        target_dir = dest_dir / rel_dir
        target_dir.mkdir(exist_ok=True)
        
        for file in files:
            src_file = Path(root) / file
            target_file = target_dir / file
            
            # Read content
            try:
                content = src_file.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                # Binary files (if any) are just copied
                shutil.copy2(src_file, target_file)
                continue
            
            # Apply substitutions
            for search, replace in substitutions.items():
                content = content.replace(search, replace)
                
            # Inject header for python files (except __init__.py if empty or specific cases)
            if target_file.suffix == ".py":
                # Ensure we insert the header after the docstring or future imports if needed,
                # but for simplicity, insert right at the top. 
                # Or wait, if there's a docstring at the very top `"""..."""`, putting a comment
                # before it is perfectly valid in Python.
                content = f"{header}\n{content}"
                
            target_file.write_text(content, encoding="utf-8")
