# Generated by RationaleVault 2.0
# Projection template version 1

"""Example events for the Timeline Extension projection."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


# Decision:
# Event payloads are immutable dataclasses inheriting from EventPayload.
#
# Why:
# Events represent historical facts that cannot change. They must be safely
# serializable to JSON/Protobuf for storage in the event ledger.

@dataclass(frozen=True)
class TaskCreatedPayload:
    """Payload for when a task is created."""
    task_id: str
    description: str
    owner: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskCreatedPayload:
        return cls(
            task_id=data["task_id"],
            description=data["description"],
            owner=data["owner"],
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "description": self.description,
            "owner": self.owner,
        }


@dataclass(frozen=True)
class TaskCompletedPayload:
    """Payload for when a task is completed."""
    task_id: str

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskCompletedPayload:
        return cls(task_id=data["task_id"])

    def to_dict(self) -> dict[str, Any]:
        return {"task_id": self.task_id}
